### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by jeromepl**
Woot woot, after working on this over a year ago, I found this dead project on my computer with a bunch of cool code that never made it to a stable version. WELL, HERE IT IS!

Still has lots of bugs and needs further testing

### CODE REVIEW

**Comment by jeromepl** [comment]
**Realtime demo:**

demo

**Review by simon-bourque — APPROVED** [review]
I don't even remember what's happening in this code so Ima just give an approve lol

**Comment by jeromepl** [comment]
Just pull it and test it!
I just removed 7.5k lines from the code, it shouldn't be too hard to understand it xD

**Review by simon-bourque — CHANGES_REQUESTED** [review]
I can record macros but I can't run any of them, nothing happens when I click my macro.  There's no error messages in the console either.

Output:
image

**Comment by jeromepl** [comment]
Have you looked in the console of the page from which you started running the macro? Like right after clicking the macro you want to run, check the console log of the current page to check for errors. Otherwise this will be really hard to debug for me without having your macro

**Comment by simon-bourque** [comment]
Console on page is empty

**Comment by jeromepl** [comment]
Alright try recording other macros. Are they all failing?

Install this [chrome extension](https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb) and go to the background page. In the dev tools, there should be a new tab. Send me the content of your macro from there

**Comment by simon-bourque** [comment]
It's reaching this
image

**Comment by simon-bourque** [comment]
image

**Comment by jeromepl** [comment]
Yup this would be a problem. The way the events are re-triggered on elements is that I save the CSS selector of the element. For example `#cref_CAMPUS_STUDENT_CENTER>a:nth-of-type(1)`. If this CSS selector is not constant (a.k.a points to a different element when you refresh the page) the extension will break.

This is why trying to recording a macro on a website like facebook is practically impossible, due to the page content being so volatile.

Try recording macros on more "static" websites to make sure.

We need a genius idea as to how to fix this problem though, because I don't know how else to save an element reference.

**Comment by simon-bourque** [comment]
I tried this website (just recorded myself changing the language of the site over and over again) http://www.lipsum.com/ and still not working

**Comment by jeromepl** [comment]
Same 'Key' warnings?

**Comment by simon-bourque** [comment]
yup
image

**Comment by jeromepl** [comment]
Alright then either try to debug it yourself or send me the JSON of the macro in chrome.storage

**Comment by simon-bourque** [comment]
check fb

**Review by simon-bourque — APPROVED** [review]

**Pull request merged**
